#!/bin/bash

# Example script demonstrating the update-todo-status endpoint
# This script shows how to dynamically update task and subtask statuses

BASE_URL="http://localhost:3001"

echo "=== Update TODO Status Examples ==="
echo ""

# Example 1: Create an enhanced TODO first
echo "1. Creating an enhanced TODO item..."
TODO_RESPONSE=$(curl -s -X POST $BASE_URL/api/enhanced-todo \
  -H "Content-Type: application/json" \
  -d '{
    "title": "EASL Guideline Query Workflow",
    "description": "Handling query to EASL Guideline Agent in background",
    "todos": [
      {
        "id": "task-101",
        "text": "Creating question query and generating context",
        "status": "pending",
        "agent": "Data Analyst Agent",
        "subTodos": [
          {
            "text": "Question : What is the DILI diagnosis for Sarah Miller according to EASL guidelines?",
            "status": "pending"
          },
          {
            "text": "Context is generated by ContextGen Agent",
            "status": "pending"
          }
        ]
      },
      {
        "id": "task-102",
        "text": "Send query to EASL Guideline Agent",
        "status": "pending",
        "agent": "Data Analyst Agent",
        "subTodos": [
          {
            "text": "Query is processing",
            "status": "pending"
          },
          {
            "text": "Result is created in canvas",
            "status": "pending"
          }
        ]
      }
    ]
  }')

TODO_ID=$(echo $TODO_RESPONSE | jq -r '.id')
echo "Created TODO with ID: $TODO_ID"
echo ""

# Wait a moment
sleep 1

# Example 2: Update main task status to "executing"
echo "2. Updating task-101 status to 'executing'..."
curl -s -X POST $BASE_URL/api/update-todo-status \
  -H "Content-Type: application/json" \
  -d "{
    \"id\": \"$TODO_ID\",
    \"task_id\": \"task-101\",
    \"index\": \"\",
    \"status\": \"executing\"
  }" | jq
echo ""

sleep 1

# Example 3: Update first subtask to "executing"
echo "3. Updating first subtask (index 0) of task-101 to 'executing'..."
curl -s -X POST $BASE_URL/api/update-todo-status \
  -H "Content-Type: application/json" \
  -d "{
    \"id\": \"$TODO_ID\",
    \"task_id\": \"task-101\",
    \"index\": \"0\",
    \"status\": \"executing\"
  }" | jq
echo ""

sleep 1

# Example 4: Update first subtask to "finished"
echo "4. Updating first subtask (index 0) of task-101 to 'finished'..."
curl -s -X POST $BASE_URL/api/update-todo-status \
  -H "Content-Type: application/json" \
  -d "{
    \"id\": \"$TODO_ID\",
    \"task_id\": \"task-101\",
    \"index\": \"0\",
    \"status\": \"finished\"
  }" | jq
echo ""

sleep 1

# Example 5: Update second subtask to "executing"
echo "5. Updating second subtask (index 1) of task-101 to 'executing'..."
curl -s -X POST $BASE_URL/api/update-todo-status \
  -H "Content-Type: application/json" \
  -d "{
    \"id\": \"$TODO_ID\",
    \"task_id\": \"task-101\",
    \"index\": \"1\",
    \"status\": \"executing\"
  }" | jq
echo ""

sleep 1

# Example 6: Update main task to "finished"
echo "6. Updating task-101 status to 'finished'..."
curl -s -X POST $BASE_URL/api/update-todo-status \
  -H "Content-Type: application/json" \
  -d "{
    \"id\": \"$TODO_ID\",
    \"task_id\": \"task-101\",
    \"index\": \"\",
    \"status\": \"finished\"
  }" | jq
echo ""

sleep 1

# Example 7: Update second task to "executing"
echo "7. Updating task-102 status to 'executing'..."
curl -s -X POST $BASE_URL/api/update-todo-status \
  -H "Content-Type: application/json" \
  -d "{
    \"id\": \"$TODO_ID\",
    \"task_id\": \"task-102\",
    \"index\": \"\",
    \"status\": \"executing\"
  }" | jq
echo ""

echo "=== Done! ==="
echo ""
echo "To view the updated TODO item, run:"
echo "curl -s $BASE_URL/api/board-items | jq '.[] | select(.id == \"$TODO_ID\")'"
